trigger: none

pool: Azure Pipelines

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    backendServiceArm: 'redo_ADO'
    backendAzureRmResourceGroupName: 'RG_SP'
    backendAzureRmStorageAccountName: 'stgsp'
    backendAzureRmContainerName: 'contsp'
    backendAzureRmKey: 'dev.tfstate'
- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
- task: TerraformTask@5
  displayName: 'Terraform Fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'redo_ADO'
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    environmentServiceNameAzureRM: 'redo_ADO'


