trigger: none

pool: 'Initial Pool'

variables: 
  workDir: '$(System.DefaultWorkingDirectory)/VM_Three-Tier_Automation/Infra-Dev'


stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: Initialize_Infra
        displayName: 'Initialize Infra'
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workDir)'
            backendServiceArm: 'redo_ADO'
            backendAzureRmResourceGroupName: 'RG_SP'
            backendAzureRmStorageAccountName: 'stgsp'
            backendAzureRmContainerName: 'contsp'
            backendAzureRmKey: 'QA.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(workDir)'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'redo_ADO'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(workDir)'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(workDir)'
            environmentServiceNameAzureRM: 'redo_ADO'
  - stage: Scan
    displayName: 'Scan'
    dependsOn: Build
    jobs:
      - job: Scan_Configs
        displayName: 'Scan_Configs'
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(workDir)'
        - script: |
            Invoke-WebRequest -Uri "https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip" -OutFile "tflint.zip"
            Expand-Archive -Path "tflint.zip" -DestinationPath "." -Force
            Remove-Item "tflint.zip"
            .\tflint.exe --chdir="$(workDir)"
          displayName: 'Run TFLint'

        # Run Checkov
        - script: |
            pip install --quiet checkov
            checkov -d "$(workDir)"
          displayName: 'Run Checkov'

  - stage: Deploy
    displayName: "Deployment"
    dependsOn: "Scan"
    jobs:
      - job: Manual_Validation
        displayName: 'Manual_Validation'
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'bhavyabharti072@gmail.com'
            approvers: 'bhavyabharti072@gmail.com'
      - job: Apply_Infra
        displayName: 'Apply_Infra'
        dependsOn: Manual_Validation
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workDir)'
            backendServiceArm: 'redo_ADO'
            backendAzureRmResourceGroupName: 'RG_SP'
            backendAzureRmStorageAccountName: 'stgsp'
            backendAzureRmContainerName: 'contsp'
            backendAzureRmKey: 'QA.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(workDir)'
            environmentServiceNameAzureRM: 'redo_ADO'