trigger: none

pool: Initial Pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    backendServiceArm: 'redo_ADO'
    backendAzureRmResourceGroupName: 'RG_SP'
    backendAzureRmStorageAccountName: 'stgsp'
    backendAzureRmContainerName: 'contsp'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    environmentServiceNameAzureRM: 'redo_ADO'