trigger: 
  - feature01_GG

pool: Initial Pool
variables: 
  workDir: '$(System.DefaultWorkingDirectory)/VM_Three-Tier_Automation/Infra-Dev'


jobs:
- job: 
  displayName: 'Terraform Installer'
  steps:
  - task: TerraformInstaller@1
    displayName: 'Terraform Installer'
    inputs:
      terraformVersion: 'latest'

- job: 
  displayName: 'Terraform Init'
  steps:
  - task: TerraformInstaller@1
    displayName: 'Terraform Installer'
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(workDir)'
      backendServiceArm: 'redo_ADO'
      backendAzureRmResourceGroupName: 'RG_SP'
      backendAzureRmStorageAccountName: 'stgsp'
      backendAzureRmContainerName: 'contsp'
      backendAzureRmKey: 'Dev01.tfstate'
  
- job: 
  displayName: 'Terraform Validate & Fmt'
  steps:
  - task: TerraformInstaller@1
    displayName: 'Terraform Installer'
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(workDir)'
      backendServiceArm: 'redo_ADO'
      backendAzureRmResourceGroupName: 'RG_SP'
      backendAzureRmStorageAccountName: 'stgsp'
      backendAzureRmContainerName: 'contsp'
      backendAzureRmKey: 'Dev01.tfstate'
  - task: TerraformTask@5
    displayName: 'Terraform Validate'
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(workDir)'
  - task: TerraformTask@5
    displayName: 'Terraform Fmt'
    inputs:
      provider: 'azurerm'
      command: 'custom'
      workingDirectory: '$(workDir)'
      outputTo: 'console'
      customCommand: 'fmt'
      environmentServiceNameAzureRM: 'redo_ADO'

- job: 
  displayName: 'Terraform Plan'
  steps:
  - task: TerraformTask@5
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(workDir)'
      backendServiceArm: 'redo_ADO'
      backendAzureRmResourceGroupName: 'RG_SP'
      backendAzureRmStorageAccountName: 'stgsp'
      backendAzureRmContainerName: 'contsp'
      backendAzureRmKey: 'Dev01.tfstate'
  - task: TerraformInstaller@1
    displayName: 'Terraform Installer'
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(workDir)'
      environmentServiceNameAzureRM: 'redo_ADO'