trigger: none

pool: Azure Pipelines

variables:
  workDir: '$(System.DefaultWorkingDirectory)/Infra-Dev'
  scName: 'redo_ADO'

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workDir)'
    backendServiceArm: 'redo_ADO'
    backendAzureRmResourceGroupName: 'RG_SP'
    backendAzureRmStorageAccountName: 'stgsp'
    backendAzureRmContainerName: 'contsp'
    backendAzureRmKey: 'dev.tfstate'
- task: TerraformTask@5
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(workDir)'
- task: TerraformTask@5
  displayName: 'Terraform Fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(workDir)'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: '$(scName)'
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(workDir)'
    environmentServiceNameAzureRM: '$(scName)'


