trigger: none

pool: Initial Pool

variables:
  workDir: '$(System.DefaultWorkingDirectory)/VM_Three-Tier_Automation/Infra-Dev'

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform Installer'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(workDir)'
    backendServiceArm: 'redo_ADO'
    backendAzureRmResourceGroupName: 'RG_SP'
    backendAzureRmStorageAccountName: 'stgsp'
    backendAzureRmContainerName: 'contsp'
    backendAzureRmKey: 'dev1.tfstate'
  displayName: 'Terraform Validate'
  
- task: TerraformTask@5  
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(workDir)'
- task: TerraformTask@5
  displayName: 'Terraform Fmt'
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(workDir)'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'redo_ADO'
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(workDir)'
    environmentServiceNameAzureRM: 'redo_ADO'