trigger: none

pool: 'Initial Pool'

variables: 
  workDir: '$(System.DefaultWorkingDirectory)/VM_Three-Tier_Automation/Infra-Dev'

parameters:
  - name: runApply
    displayName: "Do you want to run Terraform Apply?"
    type: boolean
    default: false

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: Initialize_Infra
        displayName: 'Initialize Infra'
        steps:
        - task: TerraformInstaller@1
          displayName: 'Terraform_Installer'
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@4
          displayName: 'Terraform_Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workDir)'
            backendServiceArm: 'redo_ADO'
            backendAzureRmResourceGroupName: 'RG_SP'
            backendAzureRmStorageAccountName: 'stgsp'
            backendAzureRmContainerName: 'contsp'
            backendAzureRmKey: 'QA.tfstate'
        - task: TerraformTask@5
          displayName: 'Terraform_Fmt'
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(workDir)'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'redo_ADO'
        - task: TerraformTask@5
          displayName: 'Terraform_Validate'
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(workDir)'
        - task: TerraformTask@5
          displayName: 'Terraform_Plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(workDir)'
            environmentServiceNameAzureRM: 'redo_ADO'
  - stage: Scan
    displayName: 'Scan'
    dependsOn: Build
    jobs:
      - job: Scan_Configs
        displayName: 'Scan_Configs'
        steps:
        - task: tfsec@1
          displayName: 'Run_TFSec'
          inputs:
            version: 'v1.26.0'
            dir: '$(workDir)'
            args: '--soft-fail'
          continueOnError: true
        - task: PowerShell@2
          displayName: 'Run TFLint'
          inputs:
            targetType: 'inline'
            script: |
              Invoke-WebRequest -Uri "https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip" -OutFile "tflint.zip"
              Expand-Archive -Path "tflint.zip" -DestinationPath "." -Force
              Remove-Item "tflint.zip"
              try {
                  .\tflint.exe --chdir="$(workDir)"
              } catch {
                  Write-Host "TFLint found issues, but continuing..."
              }
            continueOnError: true
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
            addToPath: true
        - task: PowerShell@2
          displayName: 'Run Checkov'
          inputs:
            targetType: 'inline'
            script: |
              python -m pip install --upgrade pip
              pip install checkov
              checkov -d "$(workDir)" --soft-fail
          continueOnError: true

  - stage: Deploy
    displayName: "Deployment"
    dependsOn: "Scan"
    condition: succeededOrFailed()
    jobs:
      - job: Manual_Validation
        displayName: 'Manual_Validation'
        pool: server
        steps:
        - task: ManualValidation@1
          displayName: 'Manual_Validation'
          inputs:
            notifyUsers: 'devopscollab101@gmail.com'
            approvers: 'devopscollab101@gmail.com'
      - job: Apply_Infra
        displayName: 'Apply_Infra'
        dependsOn: Manual_Validation
        steps:
        - task: TerraformInstaller@1
          displayName: 'Terraform_Installer'
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: 'Terraform_Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(workDir)'
            backendServiceArm: 'redo_ADO'
            backendAzureRmResourceGroupName: 'RG_SP'
            backendAzureRmStorageAccountName: 'stgsp'
            backendAzureRmContainerName: 'contsp'
            backendAzureRmKey: 'QA.tfstate'
        - task: TerraformTask@5
          displayName: 'Terraform_Apply'
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(workDir)'
            environmentServiceNameAzureRM: 'redo_ADO'
          condition: eq('${{ parameters.runApply }}', false)