trigger: none

pool: Initial Pool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'redo_ADO'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-Dev'
    environmentServiceNameAzureRM: 'redo_ADO'